### ISSUE TITLE
Usage example is not correct

### ISSUE THREAD

**Issue by iamgiolaga** [johnbeynon/render-deploy-action#3]
Hi,

I spent a while figuring out how to use this action because the syntax was formally not correct.
I would propose something like this

```
name: My Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

```

the major thing missing was the version
