### ISSUE TITLE
wait-for-success doesn't seem to be working yet?

### ISSUE THREAD

**Issue by chesampat** [johnbeynon/render-deploy-action#7]
```yaml
name: Deploy on Release to Render

on:
  release:
    types: [created]

jobs:
  deploy-prod-web:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod Web Service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-xxx
          api-key: ${{ secrets.RENDER_DEPLOY_ACTION_SECRET }}
          wait-for-success: true

  deploy-prod-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod Worker Service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-xxx
          api-key: ${{ secrets.RENDER_DEPLOY_ACTION_SECRET }}
          wait-for-success: true

  deploy-prod-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod Scheduler Service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-xxx
          api-key: ${{ secrets.RENDER_DEPLOY_ACTION_SECRET }}
          wait-for-success: true

```

**warnings**

```
6 warnings
[deploy-prod-scheduler](https://github.com/chargebackstop/platform/actions/runs/8644940191/job/23701116826)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: johnbeynon/render-deploy-action@v0.0.8. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
deploy-prod-scheduler
Unexpected input(s) 'wait-for-success', valid inputs are ['service-id', 'api-key']
[deploy-prod-worker](https://github.com/chargebackstop/platform/actions/runs/8644940191/job/23701117241)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: johnbeynon/render-deploy-action@v0.0.8. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
deploy-prod-worker
Unexpected input(s) 'wait-for-success', valid inputs are ['service-id', 'api-key']
[deploy-prod-web](https://github.com/chargebackstop/platform/actions/runs/8644940191/job/23701117494)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: johnbeynon/render-deploy-action@v0.0.8. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
deploy-prod-web
Unexpected input(s) 'wait-for-success', valid inputs are ['service-id', 'api-key']
```
